name: Trigger auto deployment for container-app-iznunw73j4n7q

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-iznunw73j4n7q-AutoDeployTrigger-f0a863bd-0d9c-4389-b6f1-bdf3cc7afdac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPIZNUNW73J4N7Q_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPIZNUNW73J4N7Q_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPIZNUNW73J4N7Q_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPIZNUNW73J4N7Q_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPIZNUNW73J4N7Q_REGISTRY_PASSWORD }}
          containerAppName: container-app-iznunw73j4n7q
          resourceGroup: todonodejspgsqlgoogleauth8a1baa8c
          imageToBuild: default/container-app-iznunw73j4n7q:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


